### ISSUE TITLE
Need a merchandise sales report for at-con pickup

### ISSUE THREAD

**Issue by rjenks** [rjenks/Con-Org#128]

**Comment by rawinans** [comment]
Robert,  Here is some more detail on what we  are looking for.
1 exporting to a spreadsheet would be great
2 for the details.  Salesid, userid,  name last, name first  Item  QTY

If its via a spreadsheet then we can filter as needed and split out the  lists.

**Comment by rjenks** [comment]
This is available under Registration - Merchandise Sales Export

**Comment by rawinans** [comment]
Robert,  running some final reports for Fencon and I noticed that some Items are missing from this report.  Invoice 68154 Should have 3 items  marked as staff membership but only 2 show up.

As reminder I create a merchandise item called Staff membership with no badge so I could keep track of  staff  members  since we some who bought at different prices.
