### ISSUE TITLE
add a 'store' page

### ISSUE THREAD

**Issue by timiller1235** [rjenks/Con-Org#83]
Have the ability to sell merchandiser on a page other than the registration page and to be able to prioritize the order they appear on that page

Items like t-shirts and even autogrpahs, photo ops or banquets

**Comment by rjenks** [comment]
You can now add a new 'catalog' bbcode item to any page.   This will be replaced with the purchase block so that the user can add the item to the shopping cart.  This will work even if the item is 'hidden'.

[catalog id=1234]

This will add catalog item 1234 to the page.  This will allow you to sell any item on any page on the site.  To create a store page, you can just have a list of these [catalog] tags in the order you want them to appear.
